### ISSUE TITLE
What is our target refresh rate?

### ISSUE THREAD

**Issue by fpdotmonkey** [tetrabiodistributed/project-tetra-display#15]
The sensors can return data at 1, 2, 4, 8, 16, 32, 64, or 128Hz.  Which do we want?

**Comment by fpdotmonkey** [comment]
Email from Daniel

> Correct ICU vents have pings 2000 times per second forgive my lazy math not converting that to Hz. This is mainly due to detecting flow changes for breath triggering. I doubt that high frequency is needed for this application but 2000:1 might be a bit of a jump. Each second should be enough to capture the majority of exhaled breath data.

**Comment by fpdotmonkey** [comment]
1Hz is the value that's been in the app for a while.

**Comment by hydronics2** [comment]
Just for reference, when reading the automotive sensor over the ADC, I was able to get pretty smooth curves using 20ms intervals (50 times/second) 50hz. pretty slow!

https://docs.google.com/spreadsheets/d/1A3mXyKlSGlLy2eQQZ9GZ_Rv0azJWEgkXXMhVJsTLFSM/edit?usp=sharing
