### ISSUE TITLE
Make a tetra Raspbian Image

### ISSUE THREAD

**Issue by fpdotmonkey** [tetrabiodistributed/project-tetra-display#43]
- [ ] has all the needed source on the PATH
- [ ] has a config to run the display program at boot

**Comment by fpdotmonkey** [comment]
this is relevant https://github.com/tetrabiodistributed/project-tetra-display/blob/master/Documentation/HowToRunAnApplicationAtLaunchOnAnRPi.md

**Comment by fpdotmonkey** [comment]
This may be useful in making the image itself https://geoffhudik.com/tech/2020/05/15/using-pi-gen-to-build-a-custom-raspbian-lite-image/

**Comment by capsulecorplab** [comment]
[PharoIoT](https://www.pharoiot.org/) may be worth looking into. Pharo is an image-based programming language that runs on a virtual machine on platforms such as raspberry pi

**Comment by mmroden** [comment]
Solved by #44, right?

**Comment by darraghbr** [comment]
No keep this open, this is for a .img file (or equivalent) that can be burnt onto a Pi with everything else pre-installed.

**Comment by mmroden** [comment]
we now have a working docker image, now need a procedure for getting things onto a pi
