### ISSUE TITLE
add CI for python unittests using GitHub Actions

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/project-tetra-display#5]
Should be doable with https://github.com/actions/checkout and https://github.com/actions/setup-python

**Comment by fpdotmonkey** [comment]
I tested by running `docker run --rm -v $PWD:/src -w "/src" ubuntu:latest bash -c "apt update && apt -y upgrade && apt install -y python3-pip python3-venv && ./setup.sh && source ./venv/bin/activate && ./runtests.sh"`, but I got this error during the behave tests
```
Behaviour Tests:
HOOK-ERROR in before_all: ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
HOOK-ERROR in after_all: ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
This is the same error from #8, so hopefully we'll be able to find a solution to both of them.

**Comment by fpdotmonkey** [comment]
If I'm understanding how this works, you're running all the tests in a docker container, including making another docker container.  Would it be possible to just run the tests in a python venv, like this

```bash
./setup.sh
. venv/bin/activate
./runtests.sh
```

**Comment by capsulecorplab** [comment]
I think it would make more sense to run the python application in a docker container than to run a docker container along side a python virtual environment, because a python virtual environment is still reliant on the system it's running on, which might as well be a docker container.

**Comment by capsulecorplab** [comment]
Also, I'd stick with `devops` for this issue label, since it's not really a feature is a part of the display code
